//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proton.VendorPortalAPI.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CENTRE_ENTITY_LIST
    {
        public string COUNTRY { get; set; }
        public string CENTRE_CODE { get; set; }
        public string CENTRE_NAME { get; set; }
        public string DEFAULT_SUN_BU { get; set; }
        public string Legal_Entity { get; set; }
        public string Centre_Email { get; set; }
        public string CountryISOCode { get; set; }
    }
}
