//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proton.VendorPortalAPI.V1.Models
{
    using Foundation.Core.EF;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class SUNEntities : EFDataContext
    {
        public SUNEntities()
            : base("name=SUNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<VENDOR> VENDORs { get; set; }
        public virtual DbSet<CENTRE_ENTITY_LIST> CENTRE_ENTITY_LIST { get; set; }
        public virtual DbSet<SERVICE_CONTACT> SERVICE_CONTACT { get; set; }
    }
}
