//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proton.VendorPortalAPI.V1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR
    {
        public string Email { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public short AccountStatusId { get; set; }
        public string Country { get; set; }
        public string CountryISOCode { get; set; }
        public string BUCode { get; set; }
    }
}
